/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WalletService } from "../wallet.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WalletCreateInput } from "./WalletCreateInput";
import { Wallet } from "./Wallet";
import { WalletFindManyArgs } from "./WalletFindManyArgs";
import { WalletWhereUniqueInput } from "./WalletWhereUniqueInput";
import { WalletUpdateInput } from "./WalletUpdateInput";
import { DepositFindManyArgs } from "../../deposit/base/DepositFindManyArgs";
import { Deposit } from "../../deposit/base/Deposit";
import { DepositWhereUniqueInput } from "../../deposit/base/DepositWhereUniqueInput";
import { InterestFindManyArgs } from "../../interest/base/InterestFindManyArgs";
import { Interest } from "../../interest/base/Interest";
import { InterestWhereUniqueInput } from "../../interest/base/InterestWhereUniqueInput";
import { LockedFundsFindManyArgs } from "../../lockedFunds/base/LockedFundsFindManyArgs";
import { LockedFunds } from "../../lockedFunds/base/LockedFunds";
import { LockedFundsWhereUniqueInput } from "../../lockedFunds/base/LockedFundsWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WalletControllerBase {
  constructor(
    protected readonly service: WalletService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Wallet })
  @nestAccessControl.UseRoles({
    resource: "Wallet",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWallet(@common.Body() data: WalletCreateInput): Promise<Wallet> {
    return await this.service.createWallet({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        balance: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Wallet] })
  @ApiNestedQuery(WalletFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Wallet",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wallets(@common.Req() request: Request): Promise<Wallet[]> {
    const args = plainToClass(WalletFindManyArgs, request.query);
    return this.service.wallets({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        balance: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Wallet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Wallet",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wallet(
    @common.Param() params: WalletWhereUniqueInput
  ): Promise<Wallet | null> {
    const result = await this.service.wallet({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        balance: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Wallet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Wallet",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWallet(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() data: WalletUpdateInput
  ): Promise<Wallet | null> {
    try {
      return await this.service.updateWallet({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          balance: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Wallet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Wallet",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWallet(
    @common.Param() params: WalletWhereUniqueInput
  ): Promise<Wallet | null> {
    try {
      return await this.service.deleteWallet({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          balance: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/deposits")
  @ApiNestedQuery(DepositFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Deposit",
    action: "read",
    possession: "any",
  })
  async findDeposits(
    @common.Req() request: Request,
    @common.Param() params: WalletWhereUniqueInput
  ): Promise<Deposit[]> {
    const query = plainToClass(DepositFindManyArgs, request.query);
    const results = await this.service.findDeposits(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        date: true,
        amount: true,

        wallet: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/deposits")
  @nestAccessControl.UseRoles({
    resource: "Wallet",
    action: "update",
    possession: "any",
  })
  async connectDeposits(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: DepositWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deposits: {
        connect: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/deposits")
  @nestAccessControl.UseRoles({
    resource: "Wallet",
    action: "update",
    possession: "any",
  })
  async updateDeposits(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: DepositWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deposits: {
        set: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/deposits")
  @nestAccessControl.UseRoles({
    resource: "Wallet",
    action: "update",
    possession: "any",
  })
  async disconnectDeposits(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: DepositWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deposits: {
        disconnect: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/interests")
  @ApiNestedQuery(InterestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Interest",
    action: "read",
    possession: "any",
  })
  async findInterests(
    @common.Req() request: Request,
    @common.Param() params: WalletWhereUniqueInput
  ): Promise<Interest[]> {
    const query = plainToClass(InterestFindManyArgs, request.query);
    const results = await this.service.findInterests(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        rate: true,
        date: true,

        wallet: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/interests")
  @nestAccessControl.UseRoles({
    resource: "Wallet",
    action: "update",
    possession: "any",
  })
  async connectInterests(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: InterestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      interests: {
        connect: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/interests")
  @nestAccessControl.UseRoles({
    resource: "Wallet",
    action: "update",
    possession: "any",
  })
  async updateInterests(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: InterestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      interests: {
        set: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/interests")
  @nestAccessControl.UseRoles({
    resource: "Wallet",
    action: "update",
    possession: "any",
  })
  async disconnectInterests(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: InterestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      interests: {
        disconnect: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/lockedFundsItems")
  @ApiNestedQuery(LockedFundsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "LockedFunds",
    action: "read",
    possession: "any",
  })
  async findLockedFundsItems(
    @common.Req() request: Request,
    @common.Param() params: WalletWhereUniqueInput
  ): Promise<LockedFunds[]> {
    const query = plainToClass(LockedFundsFindManyArgs, request.query);
    const results = await this.service.findLockedFundsItems(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        amount: true,
        startDate: true,
        endDate: true,

        wallet: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/lockedFundsItems")
  @nestAccessControl.UseRoles({
    resource: "Wallet",
    action: "update",
    possession: "any",
  })
  async connectLockedFundsItems(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: LockedFundsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lockedFundsItems: {
        connect: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/lockedFundsItems")
  @nestAccessControl.UseRoles({
    resource: "Wallet",
    action: "update",
    possession: "any",
  })
  async updateLockedFundsItems(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: LockedFundsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lockedFundsItems: {
        set: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/lockedFundsItems")
  @nestAccessControl.UseRoles({
    resource: "Wallet",
    action: "update",
    possession: "any",
  })
  async disconnectLockedFundsItems(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: LockedFundsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lockedFundsItems: {
        disconnect: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }
}
