/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsNumber,
  Min,
  Max,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { DepositCreateNestedManyWithoutWalletsInput } from "./DepositCreateNestedManyWithoutWalletsInput";
import { Type } from "class-transformer";
import { InterestCreateNestedManyWithoutWalletsInput } from "./InterestCreateNestedManyWithoutWalletsInput";
import { LockedFundsCreateNestedManyWithoutWalletsInput } from "./LockedFundsCreateNestedManyWithoutWalletsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class WalletCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  balance?: number | null;

  @ApiProperty({
    required: false,
    type: () => DepositCreateNestedManyWithoutWalletsInput,
  })
  @ValidateNested()
  @Type(() => DepositCreateNestedManyWithoutWalletsInput)
  @IsOptional()
  @Field(() => DepositCreateNestedManyWithoutWalletsInput, {
    nullable: true,
  })
  deposits?: DepositCreateNestedManyWithoutWalletsInput;

  @ApiProperty({
    required: false,
    type: () => InterestCreateNestedManyWithoutWalletsInput,
  })
  @ValidateNested()
  @Type(() => InterestCreateNestedManyWithoutWalletsInput)
  @IsOptional()
  @Field(() => InterestCreateNestedManyWithoutWalletsInput, {
    nullable: true,
  })
  interests?: InterestCreateNestedManyWithoutWalletsInput;

  @ApiProperty({
    required: false,
    type: () => LockedFundsCreateNestedManyWithoutWalletsInput,
  })
  @ValidateNested()
  @Type(() => LockedFundsCreateNestedManyWithoutWalletsInput)
  @IsOptional()
  @Field(() => LockedFundsCreateNestedManyWithoutWalletsInput, {
    nullable: true,
  })
  lockedFundsItems?: LockedFundsCreateNestedManyWithoutWalletsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { WalletCreateInput as WalletCreateInput };
