/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsNumber,
  Min,
  Max,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { DepositUpdateManyWithoutWalletsInput } from "./DepositUpdateManyWithoutWalletsInput";
import { Type } from "class-transformer";
import { InterestUpdateManyWithoutWalletsInput } from "./InterestUpdateManyWithoutWalletsInput";
import { LockedFundsUpdateManyWithoutWalletsInput } from "./LockedFundsUpdateManyWithoutWalletsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class WalletUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  balance?: number | null;

  @ApiProperty({
    required: false,
    type: () => DepositUpdateManyWithoutWalletsInput,
  })
  @ValidateNested()
  @Type(() => DepositUpdateManyWithoutWalletsInput)
  @IsOptional()
  @Field(() => DepositUpdateManyWithoutWalletsInput, {
    nullable: true,
  })
  deposits?: DepositUpdateManyWithoutWalletsInput;

  @ApiProperty({
    required: false,
    type: () => InterestUpdateManyWithoutWalletsInput,
  })
  @ValidateNested()
  @Type(() => InterestUpdateManyWithoutWalletsInput)
  @IsOptional()
  @Field(() => InterestUpdateManyWithoutWalletsInput, {
    nullable: true,
  })
  interests?: InterestUpdateManyWithoutWalletsInput;

  @ApiProperty({
    required: false,
    type: () => LockedFundsUpdateManyWithoutWalletsInput,
  })
  @ValidateNested()
  @Type(() => LockedFundsUpdateManyWithoutWalletsInput)
  @IsOptional()
  @Field(() => LockedFundsUpdateManyWithoutWalletsInput, {
    nullable: true,
  })
  lockedFundsItems?: LockedFundsUpdateManyWithoutWalletsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { WalletUpdateInput as WalletUpdateInput };
